### ISSUE TITLE
Potential use of the boundary condition files to assess background levels?

### ISSUE THREAD

**Issue by delgadocc** [geoschem/integrated_methane_inversion#166]
### Name and Institution (Required)

Name: Cristhian Delgado
Institution: University of Otago

### Description of your issue or question

Dear Lucas,

I am trying to investigate the minimum detection limits (MDL) of TROPOMI in my ROI to establish the appropriate temporal resolution of my inversions. To calculate the MDL is necessary to know the background levels and I was thinking that probably I could use the boundary conditions files that you provide with the IMI implementation. I started exploring the boundary conditions files, however, I noticed that the 'SpeciesBC_CH4' has a dimensionality of time: 8 lev: 47 lat: 46 lon: 72. I was wondering if I could use the 'write_tropomi_GC_daily_avgs.py' script to extract the daily background levels or if I'm having a conceptual error? Sorry if this is a basic question but I'm new to this so I hope you can give me a hand.

Thanks in advance for your continuous support

**Comment by msulprizio** [comment]
Hi @delgadocc. Our apologies for not responding earlier. Were you able to resolve your question? The dimensions of the existing BC files are as you outline above because they are instantaneous CH4 concentrations saved every 3 hours from a 4x5, 47-level GEOS-Chem simulation. You may replace that file with CH4 concentrations from another source and HEMCO should automatically regrid it to the model resolution and domain that you have defined in the IMI config file.
