### ISSUE TITLE
Error BoundaryCondition 

### ISSUE THREAD

**Issue by DajaE1** [geoschem/integrated_methane_inversion#186]
### Name and Institution (Required)

Name: Daja Elum
Institution: Howard University

### Description of your issue or question

Tried to run a simulation with nothing changed other than the lat/lon and date (one day) and received multiple errors regarding the BoundaryConditions .nc4 file not existing and the "HeadObject operation: Key GEOSCHEM_RESTARTS/v2020-02/initial_GEOSChem_rst.2x25_CG4.nc" does not exist. 

This has caused a failure in creating inversion results. 

![image](https://github.com/geoschem/integrated_methane_inversion/assets/123752723/5daacfa5-490f-4768-ac10-5e084e114ece)

**Comment by laestrada** [comment]
Hi @DajaE1,

This error is occurring because the boundary condition files needed to start the IMI are only currently available up until 2023-06-01. We are currently planning the release of IMI 2.0, which will include a new set of boundary conditions (with more frequent updates). For now, using an earlier time period should work.

Additionally, which version of the IMI are you using? The current released version is IMI 1.2. I ask because I see that there is no `BCversion` config variable, which comes standard in IMI 1.2. I would recommend switching to IMI 1.2 if you are not already using it. You can do this by doing:

```
$ cd /home/ubuntu/integrated_methane_inversion
$ git checkout main
$ git pull
$ git checkout imi-1.2.1
```

Let us know if you have additional issues!

--
Lucas and the IMI team

**Comment by agmeyer4** [comment]
I ran into this issue as well and was able to find this open post; however, I think it would be useful to alert the user when their config input is "out of bounds". It was not immediately clear that that was the issue until I found this post stating as much. I am using most recent IMI 1.2. Thanks!

Aaron

**Comment by valenal** [comment]
Is the AMI in AWS set up to run GEOS-Chem and get more recent GEOS-Chem BCs?
