### ISSUE TITLE
Problem setting IAM roles

### ISSUE THREAD

**Issue by djvaron** [geoschem/integrated_methane_inversion#2]
The UMI requires the user to set up an AWS IAM role to allow EC2 to access S3. 

Will provided instructions for how to do this on the Readthedocs, but when I tried, something went wrong. The role I made was not automatically applied to the instance, and when I applied it manually it still didn’t work. 

Luckily I already had an equivalent IAM role set up, but fresh AWS users may get stuck here.

**Comment by WilliamDowns** [comment]
I tried on a fresh instance with that role and it worked. I am not sure what went wrong when your instance was created since you said you did the step where you add the IAM role to the instance during instance confgiuration. Perhaps the best guidance is to remake the instance and try again with adding the role to the instance if this problem comes up.
