### ISSUE TITLE
calc_sensi running unexpectedly slowly

### ISSUE THREAD

**Issue by eastjames** [geoschem/integrated_methane_inversion#233]
### Name and Institution (Required)

Name: James East
Institution: ACMG

### Description of your issue or question

When running an inversion using the `bugfix/jacobian-perturbation-fix branch` as of commit https://github.com/geoschem/integrated_methane_inversion/commit/f9a45dddbd902fcf7fd399babbfca0ecbbe2e9b4.

The calc_sensi.py step is taking longer than I’d expect, taking 12 hours to process ~15 days for an inversion with 1300 elements. The jacobian runs each have 20 tracers. I’m running it with 32 cores on a sapphire node with 512gb memory. The time seems to be mostly spent on writing to disk. In addition, the output files are large due to having a state vector dimension in addition to lat, lon, lev.

Tagging @msulprizio @megan-he @djvaron @nicholasbalasus @laestrada as an FYI. I will test alternatives in the https://github.com/geoschem/integrated_methane_inversion/tree/bugfix/sensi_speed branch

**Comment by nicholasbalasus** [comment]
For sake of avoiding a large infrastructure change right now - to avoid the calc_sensi problem completely, could you apply the TROPOMI operator to perturbation and to base individually and then subtract them?

`operator(pert) - operator(base)` instead of `operator(pert-base)`.

**Comment by megan-he** [comment]
I also notice that in the parallelized part of the code, specifying n_jobs=-1, i.e., using all available cores (32 in my case), leads to a SIGKILL out of memory error even though not all of the allocated memory is used up according to the job stats. I need to specify n_jobs=16 or half the available cores in order to get calc_sensi to run (very slowly). (https://github.com/geoschem/integrated_methane_inversion/blob/4a46a9f2cc446f51c9ea3eb3197fd4452f6f7e61/src/inversion_scripts/calc_sensi.py#L282)
