### ISSUE TITLE
g(P) scaling of errors is squared when it shouldn't be

### ISSUE THREAD

**Issue by nicholasbalasus** [geoschem/integrated_methane_inversion#234]
### Name and Institution (Required)

Name: Nick Balasus
Institution: Harvard

### Description of your issue or question

g(P) scales the error variance for super observations. I believe it is applied too early here at L154 and should be applied after the squaring of `obs_error` on L182-L183.

https://github.com/geoschem/integrated_methane_inversion/blob/600057807ae827781239418e50c05a5b27645aae/src/inversion_scripts/invert.py#L154

https://github.com/geoschem/integrated_methane_inversion/blob/600057807ae827781239418e50c05a5b27645aae/src/inversion_scripts/invert.py#L182-L183

@laestrada @sarahhancock @megan-he

**Comment by djvaron** [comment]
Good catch, Nick. It looks like this also affects `lognormal_invert.py` through `merge_partial_k.py`:

https://github.com/geoschem/integrated_methane_inversion/blob/600057807ae827781239418e50c05a5b27645aae/src/inversion_scripts/merge_partial_k.py#L89-L94

https://github.com/geoschem/integrated_methane_inversion/blob/600057807ae827781239418e50c05a5b27645aae/src/inversion_scripts/lognormal_invert.py#L85

Since `g(P) < 1`, I think this would artificially depress the observation error when using super-observations, with the same effect as artificially increasing `gamma`.

**Comment by nicholasbalasus** [comment]
Closed by #235, thanks @laestrada!
